uwsgi: fixup name clash on solaris
Solaris defines sun to 1 which results in a compilation error:
./uwsgi.h:1646:22: error: expected identifier or ‘(’ before numeric constant struct sockaddr_un sun;

Fix #1933